name: Python Tests

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Install dependencies
      continue-on-error: true
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        
    - name: Run tests
      run: |
        pytest
